#!/usr/bin/env bash
stty -echo
echo -e "\e[?1000;1002;1006;1015h"
while read -s -n 1 char; do
  echo -n "$char" | tr '\33Mm' '\n\n\n'
done # | sed -E 's/\[<?(0|32|64);([0-9]+);([0-9]+)/\x1b[\3;\2HX/'
stty echo
